apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment

spec:
  replicas: 7

    spec:
      containers:
        - name: pawan
          image: pawan:v1
          ports:
            - containerPort: 80